name: CI
on:
  push:
    branches: [ master ]

jobs:
  filterChanges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: git-filter-repo
        uses: wmde/git-filter-repo-docker-action@v1
        with:
          privateKey: ${{ secrets.SSH_PRIVATE_KEY_CHANGES }}
          targetOrg: wikimedia
          targetRepo: wikibase-changes
          targetBranch: main
          filterArguments: >-
            --force
            --path=lib/includes/changes/
            --path=lib/includes/Changes/
            --path=lib/tests/phpunit/changes/
            --path=lib/tests/phpunit/Changes/
            --path lib/packages/wikibase/changes/
            --path .mailmap
            --path-rename=lib/includes/changes:src
            --path-rename=lib/includes/Changes:src
            --path-rename=lib/tests/phpunit/changes:tests
            --path-rename=lib/tests/phpunit/Changes:tests
            --path-rename lib/packages/wikibase/changes/:
            --message-callback 'return re.sub(b"^changes: ", b"", message)'
  secondary-ci:
    runs-on: ubuntu-latest
    id: secondary_ci
    strategy:
      fail-fast: false
      matrix:
        include:
        - env:
            DBTYPE: sqlite
            LANG: ru
            WB: both
          php-versions: '7.3'
        - env:
            DBTYPE: sqlite
            LANG: en
            WB: client
          php-versions: '7.2'
        - env:
            DBTYPE: sqlite
            LANG: en
            WB: repo
          php-versions: '7.2'
        - env:
            DBTYPE: sqlite
            LANG: ar
            WB: both
          php-versions: '7.3'
        - env:
            DBTYPE: sqlite
            LANG: en
            WB: both
          php-versions: '7.2'
        - env:
            DBTYPE: sqlite
            LANG: en
            WB: both
          php-versions: '7.3'
        - env:
            DBTYPE: sqlite
            LANG: en
            WB: both
          php-versions: '7.4'
    steps:
    - name: Echo Env
      id: echo_env
      run: |
        (i am prone to fail so we can test email notifications) env
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
    - name: install.sh
      env: ${{ matrix.env }}
      run: |
        bash ./build/travis/install.sh
    - name: Apply WB settings
      env: ${{ matrix.env }}
      run: |
        bash ./build/travis/mw-apply-wb-settings.sh
    - name: Update DB
      env: ${{ matrix.env }}
      run: |
        bash ./build/travis/update-db.sh
    - name: Run script
      env: ${{ matrix.env }}
      run: |
        bash ./build/travis/script.sh
    - name: Send mail
      if: ${{ failure() }}
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job result TEST
        # Literal body:
        body: Step ${{ job.id }} failed for version ${{ matrix.php-versions }}!
        to: noa.rave@wikimedia.de
        from: Wikibase Github Action CI
